### ISSUE TITLE
feat: user login

### ISSUE THREAD

**Issue by CUexter** [CUexter/Tweet#13]
This feature request aims to add user login functionality to the twitter clone app. The following functionalities need to be implemented:

### UI

- Show a login form on the login page
- Show an error message if the user provides an invalid username/password
- Redirect the user to the home page if the login is successful
- Show a logout button on the home page if the user is already logged in

### Server-side functionality:

- Authenticate the user using the username and password provided
- Store the user's session information, such as the username, display name, and whether the user is an admin
- Invalidate the user's session when the user logs out

### Remark:
- Login should be done on client-side, while authentication should be done on server-side

**Comment by yann5280** [comment]
Logout button is not created. Instead, can implement in a sidebar easily with the following few line codes.
```
import { signOut } from "next-auth/react";
// Assign the signOut() function with a click of signout button
// e.g. onClick={() => signOut()}
```
